# Generated by Django 4.1.2 on 2022-11-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата получения обращения')),
            ],
        ),
    ]
